name: Shea Taylor
favicon: null
layout_spectrum: 0.23297
typography_spectrum: 0.73186
title: SHEA TAYLOR PHOTOGRAPHER
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf3ed'
    - '#1b2117'
    - '#5c5751'
    - '#807876'
    - '#b2a7a5'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
